version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  django:
    image: django-learningapp
    container_name: django_container
    command:
      - sh
      - -c
      - |
        python3 manage.py collectstatic --no-input --clear
        python3 manage.py makemigrations
        python3 manage.py migrate
        python3 manage.py load_sample_data
        gunicorn simplystudy.wsgi --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - /home/konradwojda/learning-app/:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

volumes:
  postgres_db:
    driver: local
