# Generated by Django 4.2.1 on 2023-09-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("university", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="questionset",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="questionset",
            name="questions",
        ),
        migrations.AddField(
            model_name="question",
            name="question_set",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.questionset",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionset",
            name="name",
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name="TestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text answer"),
                            ("MULTIPLE", "Multiple choice"),
                            ("SINGLE", "Single choice"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_questions",
                        to="questions.test",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="test",
            name="question_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="questions.questionset",
            ),
        ),
        migrations.AddField(
            model_name="questionset",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="questions.course",
            ),
        ),
    ]
