# Generated by Django 4.2.1 on 2023-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionset",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
