# Generated by Django 4.2.1 on 2023-10-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_course_test_remove_question_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
