# Generated by Django 4.2.1 on 2023-11-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_userresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestion",
            name="question",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text answer"),
                    ("MULTIPLE", "Multiple choice"),
                    ("SINGLE", "Single choice"),
                    ("TF", "True or false"),
                ],
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="TestQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_choices",
                        to="questions.testquestion",
                    ),
                ),
            ],
        ),
    ]
