# Generated by Django 4.2.1 on 2023-11-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_testquestion_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testquestion",
            name="is_true",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
